-- AlterTable
ALTER TABLE "Bus" ADD COLUMN     "lowerSeaterPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lowerSleeperPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "upperSleeperPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
